# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: erho <erho@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/03/06 14:06:13 by sewopark          #+#    #+#              #
#    Updated: 2024/05/05 20:10:02 by erho             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	= minishell
INCLUDE	= ../include/
CC		= cc
RM		= rm -f
CFLAGS	= -Wall -Wextra -Werror

LEXER	= lexer/lexer.c
PARSER	= parser/handling_dollar.c parser/parser.c parser/set_tree_utils.c \
			parser/set_tree.c parser/insert_tree.c parser/insert_tree_utils.c \
			parser/join.c
TOKEN	= tokenizer/tokenizer.c tokenizer/tokenizer_utils.c
TEST	= test/_test_env_lst.c test/_test_main.c
PARSE	= bool_check.c free.c $(LEXER) $(PARSER) $(TOKEN) $(TEST)
			
SRCS	= $(PARSE)
OBJS	= $(SRCS:%.c=%.o)
LIBFT	= ../libft/libft.a

all: $(NAME)

$(NAME): $(OBJS) $(LIBFT)
	$(CC) $(CFLAGS) $(LIBFT) $(OBJS) -lreadline -o $(NAME)

%.o : %.c
	$(CC) $(CFLAGS) -I $(INCLUDE) -c $< -o $@

$(LIBFT) :
	make -C ../libft all

clean:
	make clean -C ../libft
	$(RM) $(OBJS)

fclean: clean
	make fclean -C ../libft
	$(RM) $(NAME)

re:
	make fclean
	make all

.PHONY : all clean fclean re
